# Generated by Django 3.2.9 on 2021-11-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_attributeoptions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attributeoptions',
            table='attribute_options',
        ),
    ]
