# Generated by Django 3.2.9 on 2021-11-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_attributeoptions_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(related_name='attributes', through='management.ProductAttribute', to='management.Attribute'),
        ),
    ]
